### ISSUE TITLE
Cannot print import-like string for current file

### ISSUE THREAD

**Issue by DyspC** [danielyxie/bitburner#2297]
It looks like something tries to replace the import text recursively and crashes

```
RUNTIME ERROR
recurseCrash.js@home

Maximum call stack size exceeded
stack:
RangeError: Maximum call stack size exceeded
at String.replace ()
at _getScriptUrls (file:///D:/SteamLibrary/steamapps/common/Bitburner/resources/app/main.bundle.js:19:83552)
at file:///D:/SteamLibrary/steamapps/common/Bitburner/resources/app/main.bundle.js:19:83907
at String.replace ()
at _getScriptUrls (file:///D:/SteamLibrary/steamapps/common/Bitburner/resources/app/main.bundle.js:19:83552)
at file:///D:/SteamLibrary/steamapps/common/Bitburner/resources/app/main.bundle.js:19:83907
at String.replace ()
at _getScriptUrls (file:///D:/SteamLibrary/steamapps/common/Bitburner/resources/app/main.bundle.js:19:83552)
at file:///D:/SteamLibrary/steamapps/common/Bitburner/resources/app/main.bundle.js:19:83907
at String.replace ()
```

- recurseCrash.js
```js
/** @param {NS} ns **/
export async function main(ns) {
    ns.tprintf('import * as lib from "./recurseCrash.js"')
}
```

**Comment by theit8514** [comment]
This is a known limitation of the import system. It also parses comments so beware of that. The permanent fix is to replace the regex replace with the acorn AST parser.

As a workaround you can split the string inside the word 'from' e.g. `ns.tprintf('import * as lib fr' + 'om "./recurseCrash.js"')`.
