### ISSUE TITLE
getBlackOpRank() Runtime Error

### ISSUE THREAD

**Issue by Playegage** [danielyxie/bitburner#2841]
export async function main(ns) {
    await ns.tail();
    let ops = await ns.bladeburner.getBlackOpNames();	
    for(var o=0;o<ops.length;o++){
	await ns.print(ops[o]+": "+await ns.bladeburner.getBlackOpRank(o));
    }
}

Running the above script gave the following error. 

RUNTIME ERROR
test.js@home

t.toLowerCase is not a function
stack:
TypeError: t.toLowerCase is not a function
at I.getActionIdFromTypeAndName (file:///D:/SteamLibrary/steamapps/common/Bitburner/resources/app/main.bundle.js:1:338166)
at l (file:///D:/SteamLibrary/steamapps/common/Bitburner/resources/app/main.bundle.js:19:275218)
at Object.getBlackOpRank (file:///D:/SteamLibrary/steamapps/common/Bitburner/resources/app/main.bundle.js:19:276437)
at Module.main (blob:file:///81434ffd-cf24-4236-80d0-8ccc34afb949:8:51)

**Comment by Playegage** [comment]
The same error happened when changed to getActionCurrentLevel()

**Comment by Playegage** [comment]
nevermind, i see the problem. Im just a fool.
