### ISSUE TITLE
savegame corruption - sort of

### ISSUE THREAD

**Issue by FreifunkerEZ** [danielyxie/bitburner#3599]
## Hello!

It's me again. (see also #3554 )

I have continued to play this save and it worked okay. As I said, I thought I had a way to get rid of the corruption (CTRL-F5), but that did not work this time. So here we are. I may think, it has something to do with these console messages:

```
LoadingScreen.tsx:64 Error: Router called before initialization
    at Object.Ct (GameRoot.tsx:115:9)
    at b (MessageHelpers.ts:60:14)
    at Object.checkCounters (engine.tsx:214:7)
    at Object.updateGame (engine.tsx:142:12)
    at Object.start (engine.tsx:459:14)
    at Object.load (engine.tsx:404:14)
    at LoadingScreen.tsx:53:20
    at async LoadingScreen.tsx:49:5
	
AllServers.ts:96 Hostname of the server thats being added: ecorp
	y @ AllServers.ts:96
	b @ AllServers.ts:171
	load @ engine.tsx:435
	(anonymous) @ LoadingScreen.tsx:65
	Promise.catch (async)
	(anonymous) @ LoadingScreen.tsx:63
	(anonymous) @ LoadingScreen.tsx:69
	Du @ react-dom.production.min.js:262
	t.unstable_runWithPriority @ scheduler.production.min.js:18
	Wi @ react-dom.production.min.js:122
	Cu @ react-dom.production.min.js:261
	(anonymous) @ react-dom.production.min.js:261
	F @ scheduler.production.min.js:16
	x.port1.onmessage @ scheduler.production.min.js:12

AllServers.ts:97 The server that already has this IP is: ecorp
	y	@	AllServers.ts:97
	b	@	AllServers.ts:171
	load	@	engine.tsx:435
	(anonymous)	@	LoadingScreen.tsx:65
	Promise.catch (async)		
	(anonymous)	@	LoadingScreen.tsx:63
	(anonymous)	@	LoadingScreen.tsx:69
	Du	@	react-dom.production.min.js:262
	t.unstable_runWithPriority	@	scheduler.production.min.js:18
	Wi	@	react-dom.production.min.js:122
	Cu	@	react-dom.production.min.js:261
	(anonymous)	@	react-dom.production.min.js:261
	F	@	scheduler.production.min.js:16
	x.port1.onmessage	@	scheduler.production.min.js:12
	
AllServers.ts:98 Uncaught (in promise) Error: Error: Trying to add a server with an existing IP
    at y (AllServers.ts:98:11)
    at b (AllServers.ts:171:5)
    at Object.load (engine.tsx:435:7)
    at LoadingScreen.tsx:65:18
    at async LoadingScreen.tsx:49:5
```
Version is 00628a8c from https://danielyxie.github.io/bitburner/

### Savefile
[RECOVERY_BITBURNER_1651561400.zip](https://github.com/danielyxie/bitburner/files/8608792/RECOVERY_BITBURNER_1651561400.zip)

### Extra hint!
I use a laptop and have it cranked down really slow, so the fans don't kick on. Could this be a fun race-condition, which only shows up on SUUUPER slow machines.

And indeed! After taking of the handbreak, CTRL-F5 loaded the game nicely after 3 attempts have failed before.

### Handbreak
Go into windows system settings at `Control Panel\Hardware and Sound\Power Options\Edit Plan Settings` then `Change advanced power settings', there `Processor power management, Maximum power state` reduce 100 to 99. Which is not like a 1% reduction, but rather feels like 80% reduction. Which is okay for most things, if you can tolerate waiting a bit more than fans blaring. 

![grafik](https://user-images.githubusercontent.com/17656471/166416179-3ec27eb1-5521-4608-9cca-280d4649433c.png)

**Comment by phyzical** [comment]
@FreifunkerEZ hey there, when this occurred were you augmenting or changing bitnode or were you just idling the game?

**Comment by FreifunkerEZ** [comment]
No. I was going back to the game. 

I usually hit "BACK" in the browser in the evening to go to the Matrix screen. Then click on the BITBURNER logo to go forwards. (I do not trust the game to properly calculate offline rewards when the game stays open, but the computer is hibernated). And after I clicked BITBURNER, the spinner showed up, took quite some time and then crashed during initialization.

**Comment by Snarling** [comment]
Based on the error it was trying to add the ecorp server twice. I personally can't think why this would happen specifically on a very slow computer.

I will say your way of reloading the game is probably an outlier (idling on the matrix screen). I'm not sure this could be related to your issue but if you run into issues again you might want to just try closing the tab (or closing the whole browser) and reopening it, maybe make a shortcut or a bookmark to make it easier to reload the game instead of just idling on the matrix screen.

**Comment by FreifunkerEZ** [comment]
Okies. Will try. I'll close this for now.

I am glad we talked about it and others might find it.
