### ISSUE TITLE
New check "Infinite loop without sleep detected. 1000 ns functions were called without sleep" causing existing scripts to fail

### ISSUE THREAD

**Issue by Penumbra69** [danielyxie/bitburner#3707]
I refreshed my browser yesterday and saw a large amount of release notes and updates, which is awesome!

- [x ] Version of the game: Bitburner v1.7.0 (b71418b0)

Unfortunately post-updates, my augmentation sorting scripts that have been working nicely for months have stopped working with the error message:
```
RUNTIME ERROR
/orobouros/test.js@home (PID - 3984)

Infinite loop without sleep detected. 1000 ns functions were called without sleep. This will cause your UI to hang.
stack:
Error: Infinite loop without sleep detected. 1000 ns functions were called without sleep. This will cause your UI to hang.
at value (https://danielyxie.github.io/bitburner/dist/main.bundle.js:1:406956)
at Object.getAugmentationsFromFaction (https://danielyxie.github.io/bitburner/dist/main.bundle.js:1:307856)
at home//orobouros/test.js:98:24
at Array.sort ()
at Module.main (home//orobouros/test.js:91:15)
```

At first I thought "1000ms, one second - that's fair.." but I just realized the message says 1000`ns`?!?!?  
We're supposed to have every function we write complete within one (1) `1ms`?!  That's a pretty low bar... 
Is there an "opt-out" flag we can set which says "I know my UI may pause, and it's fine"???

The code which this message is complaining about is a complex sort(), sure - it's part of a series of array `filter().map().sort()` routines to fold the faction/augmentation data and sort it into a manner my other systems can use.  It's been this way for months, and may not be the most performant piece of code I've ever written, but it runs once every 10 seconds and has never caused the game to freeze.  To complicate matters, I've yet to find a way to `await ns.sleep(1)` inside of those array prototypes without causing issues, since they are not `async` methods.

In order to highlight the issue - I've reduced the code to reproduce to just my collecting/sorting of faction augs, and in doing so have seen the timing from initiating the call to the crash above happening within 2ms .. not 1000ns true, but that's pretty OK for me and my needs.  I printed the `Date.now()` just before calling my sort() function, wrapping it in a try/catch - and emitting the moment the system raised the exception.

```
[home ~/]> run time_crash.js
Running script with 1 thread(s), pid 4008 and args: [].
time_crash.js: Current Time: 1653237510628
time_crash.js: Crash time: 1653237510630
time_crash.js: Error Message: Infinite loop without sleep detected. 1000 ns functions were called without sleep. This will cause your UI to hang.
time_crash.js: Total time: 2ms
```

Here is my reduced "time_crash.js" script -- please don't make this a code review :) I'm happy with my messy ways.  
Instead, please tell me why this code is now considered to be broken, and is not allowed to run any more.  This is a standard functional array handling cascade that I really don't want to decompose just to satisfy the ability to `await ns.sleep(1)` which would in turn make this sort routine take a LOT LONGER 🗡️ ..

```js
/** @param {NS} ns */
export async function main(ns) {
    let myAugs = []

    let flargh = ns.getPlayer()
        .factions
        .map(f => {
            return ns.getAugmentationsFromFaction(f)
                .sort((a, b) => { return ns.getAugmentationPrice(b) - ns.getAugmentationPrice(a) })
                .map(fl => {
                    return {
                        'faction': f,
                        'frep': ns.getFactionRep(f),
                        'aug': fl,
                        'cost': ns.getAugmentationPrice(fl),
                        'rep': ns.getAugmentationRepReq(fl),
                        'pre': ns.getAugmentationPrereq(fl),
                        'stats': ns.getAugmentationStats(fl)
                    }
                }).filter(fa => {
                    return !myAugs.includes(fa.aug) || fa.aug.startsWith("NeuroFlux Governor")
                })
        }).flat()

    // The prior .flat() and the next .sort() used to be chained together functionally, 
    // I've decomposed them here to show the issue

    await ns.sleep(1) // Ok, we've slept for sure, now .. 
    let now = Date.now()
    ns.tprint("Current Time: " + now)
    
    // Added try/catch to capture the moment the exception raises
    try {
        flargh = flargh.sort((a, b) => {
            // Neuroflux are special case - we can always afford, but want to buy those LAST in line.
            // Unsatisfied requirements go 2nd to last, those will get satisfied as we roll
            // top is most expensive - may not have the required rep for it yet.
            let a_pre = a.pre.filter(r => { return !myAugs.includes(r) })
            let b_pre = b.pre.filter(r => { return !myAugs.includes(r) })
            let a_nfg = ns.getAugmentationsFromFaction(a.faction).filter(fl => {
                return (!myAugs.includes(fl) || fl.startsWith("NeuroFlux Governor"))
            })
            let a_nfg_plus = a_nfg.length
            let a_nfg_rep = (a_nfg.length > 0 ? a.frep : 0)

            let b_nfg = ns.getAugmentationsFromFaction(b.faction).filter(fb => {
                return !myAugs.includes(fb) || fb.startsWith("NeuroFlux Governor")
            })
            let b_nfg_plus = b_nfg.length
            let b_nfg_rep = (b_nfg.length > 0 ? b.frep : 0)

            return ((a.aug.startsWith("NeuroFlux Governor") ?
                (b.aug.startsWith("NeuroFlux Governor") ?
                    b_nfg_plus === a_nfg_plus ? (a_nfg_rep < b_nfg_rep ? 1 : a_nfg_rep == b_nfg_rep ? 0 : -1) : a_nfg_plus - b_nfg_plus
                    : 1) : // At this point we need to see if the faction has others.
                b.aug.startsWith("NeuroFlux Governor") ? -1 :
                    a_pre.length > 0 ? b_pre.length > 0 ? 0 : 1 :
                        b_pre.length > 0 ? -1 :
                            b.cost - a.cost))
        })

    } catch (e) {
        ns.tprint("Crash time: " + Date.now())
        ns.tprint("Error Message: ", e.message)
        ns.tprint("Total time: " , Date.now() - now, "ms")
    }

}

```

**Comment by Penumbra69** [comment]
OMG - Did I misread this entirely!??!

Is it actually saying "1000 NS Calls" not "1000 ns"...

If that's the case - this seems like a very spurious error state.  
There's no infinite loop -- It's just a complex sort!!!!

**Comment by Penumbra69** [comment]
Closing the issue for now - this is not the correct write-up.
