### ISSUE TITLE
ns.singularity.manualHack() crashing

### ISSUE THREAD

**Issue by robinsky** [danielyxie/bitburner#3762]
RUNTIME ERROR
mooz.js@home (PID - 130)

Cannot read properties of undefined (reading 'scriptRef')
stack:
TypeError: Cannot read properties of undefined (reading 'scriptRef')
at l (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:1:202436)
at Object.ft [as hack] (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:1:773537)
at file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:19:1212688
at value (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:19:1227546)
at Object.manualHack (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:1:294225)
at manHack (home/mooz.js:32:18)
at async Module.main (home/mooz.js:40:17)

This was running fine on 1.7.0 but since the steam updates (infinite loop safety net update and fix ns1 scripts today calling manualHack() causes this error in 1.7.0 (cb7f3b17).

**Comment by robinsky** [comment]
Also await ns.prompt() is triggering an infinite loop warning, perhaps because the user does not respond within 2000 ms, but was not doing so prior to the infinite loop safety net update. 

RUNTIME ERROR
retarget.js@home (PID - 149)
Args: ["neo-net", 5]

Potential infinite loop without sleep detected. The game spent 2000ms stuck in this script. (Are you using 'asleep' by mistake?)
stack:
Error: Potential infinite loop without sleep detected. The game spent 2000ms stuck in this script. (Are you using 'asleep' by mistake?)
at value (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:19:1227373)
at Object.prompt (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:1:294225)
at Module.main (home/retarget.js:43:27)

**Comment by hydroflame** [comment]
ok this one I figured out but not pushed yet
