### ISSUE TITLE
Crash in ns.sprintf

### ISSUE THREAD

**Issue by smeehrrr** [danielyxie/bitburner#3767]
Stack:
RUNTIME ERROR
sprintf.js@home (PID - 15)

n.substring is not a function
stack:
TypeError: n.substring is not a function
at c (file:///C:/Steam/steamapps/common/Bitburner/resources/app/dist/vendor.bundle.js:30:257145)
at o (file:///C:/Steam/steamapps/common/Bitburner/resources/app/dist/vendor.bundle.js:30:254315)
at value (file:///C:/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:19:1227016)
at Object.sprintf (file:///C:/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:1:294124)
at Module.main (home/sprintf.js:3:13)
at executeJSScript (file:///C:/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:19:101335)

Script to repro:

export async function main(ns) {
	let x = ns.sprintf('%1$s', 'test' );
}

Version: BitBurner v1.7.0 (6a2e5b06)

This was working fine before the last Steam update.

**Comment by hydroflame** [comment]
on it

**Comment by hydroflame** [comment]
fxied
