### ISSUE TITLE
createCorporation second argument inverted?

### ISSUE THREAD

**Issue by smeehrrr** [danielyxie/bitburner#4047]
A script that previously worked calls ns.corporation.createCorporation( 'name', true ).  On 2.0.2 this threw:

RUNTIME ERROR
startup-corporation.js@home (PID - 86)

cannot use seed funds outside of BitNode 3
stack:
Error: cannot use seed funds outside of BitNode 3
at file:///C:/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:19:339235
at file:///C:/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:19:339538
at Object.value [as createCorporation] (file:///C:/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:19:1233545)
at Module.main (home/startup-corporation.js:25:27)
at executeJSScript (file:///C:/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:19:119700)

Switching the parameter to false allowed it to proceed. So either the code is bugged or the docs are bugged.

**Comment by hydroflame** [comment]
Fixed in next patch
