### ISSUE TITLE
purchase4SMarketData() bug

### ISSUE THREAD

**Issue by Penndrageist** [danielyxie/bitburner#607]
Running the below line in my stock-master script gives the below error.
`while(!ns.purchase4SMarketData()) await ns.sleep(TINY_SLEEP);`

`Script runtime error: 
Server Ip: 72.2.8.8
Script name: stock-master.ns
Args:["--fracH", 0.0001]
getStockMarket4SDataCost is not defined
stack:
ReferenceError: getStockMarket4SDataCost is not defined
at purchase4SMarketData (https://danielyxie.github.io/bitburner/dist/engine.bundle.js:1:399412)
at Object.purchase4SMarketData (https://danielyxie.github.io/bitburner/dist/engine.bundle.js:1:199544)
at Module.main (blob:https://danielyxie.github.io/b80d2ed8-b2f2-4f10-8026-cef1b7915cef:235:15)
at executeJSScript (https://danielyxie.github.io/bitburner/dist/engine.bundle.js:1:1057867)
at P (https://danielyxie.github.io/bitburner/dist/engine.bundle.js:1:199758)
at w (https://danielyxie.github.io/bitburner/dist/engine.bundle.js:1:203831)`

**Comment by danielyxie** [comment]
Should be fixed in v0.47.0. If not let me know. Thanks!
